# Generated by Django 4.1.7 on 2023-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C2BMpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(blank=True, max_length=200)),
                ('transID', models.CharField(blank=True, max_length=200)),
                ('transTime', models.CharField(blank=True, max_length=200)),
                ('transAmount', models.CharField(blank=True, max_length=200)),
                ('businessShortCode', models.CharField(blank=True, max_length=200)),
                ('billRefNumber', models.CharField(blank=True, max_length=200)),
                ('invoiceNumber', models.CharField(blank=True, max_length=200)),
                ('orgAccountBalance', models.CharField(blank=True, max_length=200)),
                ('thirdPartyTransID', models.CharField(blank=True, max_length=200)),
                ('mSISDN', models.CharField(blank=True, max_length=200)),
                ('firstName', models.CharField(blank=True, max_length=200)),
                ('middleName', models.CharField(blank=True, max_length=200)),
                ('lastName', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LNMTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantRequestID', models.CharField(blank=True, max_length=200)),
                ('checkoutRequestID', models.CharField(blank=True, max_length=200)),
                ('resultCode', models.CharField(blank=True, max_length=200)),
                ('resultDesc', models.CharField(blank=True, max_length=200)),
                ('amount', models.CharField(blank=True, max_length=200)),
                ('mpesaReceiptNumber', models.CharField(blank=True, max_length=200)),
                ('balance', models.CharField(blank=True, max_length=200)),
                ('transactionDate', models.CharField(blank=True, max_length=200)),
                ('phoneNumber', models.CharField(blank=True, max_length=200)),
                ('target_account', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
