# Generated by Django 4.1.7 on 2023-03-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_lnmtransactions_lnmtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointLmnC2BTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_code', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('target_accont', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('type', models.CharField(choices=[('DEPOSIT', 'DEPOSIT')], max_length=10)),
                ('transaction_time', models.DateTimeField()),
            ],
        ),
    ]
